Resources:
  tableAuthenticateSession:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Popla
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
